### ISSUE TITLE
Simulation failed when attempting the physical parameters estimation

### ISSUE THREAD

**Issue by Jun-Pu** [y-zheng18/PhysAvatar#1]
Hi, thanks so much for the inspiring&elegant work!

I got stuck at this step `bash scripts/phys_param_estimation.sh` 

I'm not familiar with Codim-IPC and I'm unsure of the specific reason for the error; Could you please help to have a look?

I used Actor01-Sequence01-4x videos as instructed. The logs are as follows:

> (PhysAvatar-py310) root@ubuntu20:/home/vipuser/Setting_PhysAvatar# bash scripts/phys_param_estimation.sh
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:05<00:00,  2.98it/s]
wandb: Using wandb-core as the SDK backend. Please refer to https://wandb.me/wandb-core for more information.
wandb: Currently logged in as: junpuzhang-2022. Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.18.2
wandb: Run data is saved locally in output/garment_param_estimation_a1_s1/wandb/run-20241002_153302-2k7gewqg
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run param_optim_a1_s1
wandb: ⭐️ View project at https://wandb.ai/junpuzhang-2022/PhysAvatar
wandb: 🚀 View run at https://wandb.ai/junpuzhang-2022/PhysAvatar/runs/2k7gewqg
wandb initialized param_optim_a1_s1
===============================================================
Evaluating individual: {'algI': '1', 'clothI': '2', 'garmentName': 'a1_s1_460_14_cloth', 'seqName': 'a1_s1_460_14_smplx', 'frame_num': 14, 'num_boundary_points': 228, 'membEMult': 1.0, 'bendEMult': 1.0, 'density': 320, 'cpu_a': 0, 'cpu_b': 4}
taskset -c 0-4 python3 codim_ipc_sim.py 1 2 a1_s1_460_14_cloth 1.000000 1.000000 a1_s1_460_14_smplx 320 14 228
===============================================================
Evaluating individual: {'algI': '1', 'clothI': '2', 'garmentName': 'a1_s1_460_14_cloth', 'seqName': 'a1_s1_460_14_smplx', 'frame_num': 14, 'num_boundary_points': 228, 'membEMult': 1.05, 'bendEMult': 1.0, 'density': 320, 'cpu_a': 5, 'cpu_b': 9}
taskset -c 5-9 python3 codim_ipc_sim.py 1 2 a1_s1_460_14_cloth 1.050000 1.000000 a1_s1_460_14_smplx 320 14 228
===============================================================
===============================================================
Evaluating individual: {'algI': '1', 'clothI': '2', 'garmentName': 'a1_s1_460_14_cloth', 'seqName': 'a1_s1_460_14_smplx', 'frame_num': 14, 'num_boundary_points': 228, 'membEMult': 1.0, 'bendEMult': 1.0, 'density': 325, 'cpu_a': 15, 'cpu_b': 19}
Evaluating individual: {'algI': '1', 'clothI': '2', 'garmentName': 'a1_s1_460_14_cloth', 'seqName': 'a1_s1_460_14_smplx', 'frame_num': 14, 'num_boundary_points': 228, 'membEMult': 1.0, 'bendEMult': 1.05, 'density': 320, 'cpu_a': 10, 'cpu_b': 14}
taskset -c 15-19 python3 codim_ipc_sim.py 1 2 a1_s1_460_14_cloth 1.000000 1.000000 a1_s1_460_14_smplx 325 14 228
taskset -c 10-14 python3 codim_ipc_sim.py 1 2 a1_s1_460_14_cloth 1.000000 1.050000 a1_s1_460_14_smplx 320 14 228
Simulation failed, check CPU affinity
Loss: inf
===============================================================
Simulation failed, check CPU affinity
Loss: inf
===============================================================
Simulation failed, check CPU affinity
Loss: inf
===============================================================
Simulation failed, check CPU affinity
Loss: inf
===============================================================
Simulation failed, check CPU affinity

Thanks in advance!

**Comment by y-zheng18** [comment]
Hi, I'm running those simulations in parallel using different CPU segments, where `taskset -c {}-{}` specifies which CPU the subprocess will use. The error might mean that there's no available CPU to run the job. You can try to lower the CPU number used in each subprocess, or just delete `taskset -c {}-{}` in ![here](https://github.com/y-zheng18/PhysAvatar/blob/main/codim_ipc_finite_diff.py#L53) (which would make the simulation much slower).
