### ISSUE TITLE
Missing CMakeLists.txt in Codim-IPC

### ISSUE THREAD

**Issue by lxxue** [y-zheng18/PhysAvatar#2]
Hi, thanks for the great work.

I tried to build the `Codim-IPC` with `python build.py` while get error of missing `CMakeLists.txt` in different places.

I downloaded the following files from the original [repo](https://github.com/ipc-sim/Codim-IPC/tree/main) and things seem to work afterwards:
```
--Codim-IPC
  --CMakeLists.txt
  --Externals/CMakeLists.txt
  --Externals/pybind11/CMakeLists.txt
  --Externals/pybind11-master/CMakeLists.txt
```

**Comment by y-zheng18** [comment]
Thanks! I pushed it now :)
