### ISSUE TITLE
Request for Tutorial on Animating Characters Using MIXAMO Data

### ISSUE THREAD

**Issue by se122811** [y-zheng18/PhysAvatar#4]
First of all, thank you for sharing this amazing work and for making the code publicly available. It has been incredibly helpful for understanding and applying the techniques in your paper.

I noticed that the functionality to animate characters using MIXAMO data is mentioned in the repository, but the corresponding tutorial or instructions do not seem to be available yet. 

Could you kindly provide an update on when this tutorial might be released? Alternatively, if there are any preliminary instructions or steps that we could follow in the meantime, it would be greatly appreciated.

Thank you for your hard work and for your contributions to the community. I look forward to your response!

**Comment by y-zheng18** [comment]
Hi, 

I can provide preliminary instructions. The basic logic is to obtain the animated mesh sequences of garment and the underlining human body, and the rest is simulation part which is already included in the repo. To use mixamo motion, (a) combine the human mesh and smplx in blender into single mesh and export to obj; (b) upload the obj mesh to mixamo, use auto rigging to rig it, then choose any motion to animate the sequence, and download the fbx file; (c) import fbx file to blender, separate the human mesh and smplx mesh, export the obj sequences; (d) extract garment part from the full-body human mesh sequence, and use the garment and smplx mesh for simulation.

**Comment by se122811** [comment]
Thank you for your kind response. I will proceed as per the method you explained.
